# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6cad81e6b6e61a2f7ed852d12894fa5c"
name = "0608"
handle = "0608"
application_url = "https://households-armor-nw-indianapolis.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://households-armor-nw-indianapolis.trycloudflare.com/auth/callback",
  "https://households-armor-nw-indianapolis.trycloudflare.com/auth/shopify/callback",
  "https://households-armor-nw-indianapolis.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
